services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./data/prepared:/var/opt/mssql/csv
    restart: unless-stopped

  preprocessing:
    image: python:3.13-slim
    container_name: olist-preprocessing
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    working_dir: /app
    command: python scripts/preprocess.py

volumes:
  sqlserver_data: